module ArrayUtils

using Statistics: Statistics
using Base.Threads: @threads, nthreads

export seed_factor_ladder,
    build_schedule_from_seeds,
    build_schedule_from_seeds!,
    coarsen2d_mean,
    coarsen2d_mean!,
    coarsen3d_horizontal_mean,
    coarsen3d_horizontal_mean!,
    coarsen3d_vertical_mean,
    coarsen3d_vertical_mean!,
    conv3d_block_mean,
    conv3d_block_mean!,
    conv3d_valid_box_mean,
    conv3d_valid_box_mean!,
    conv3d_valid_box_product_mean,
    conv3d_valid_box_product_mean!,
    valid_box_output_extent,
    uniform_stride_for_valid_box,
    valid_box_anchor_starts,
    conv3d_valid_box_mean_at_starts,
    conv3d_valid_box_mean_at_starts!,
    conv3d_valid_box_product_mean_at_starts,
    conv3d_valid_box_product_mean_at_starts!,
    coarsen_fields_horizontal,
    coarsen_fields_vertical,
    coarsen_dz_profile_2x,
    coarsen_dz_profile_factor,
    full_domain_mean_3d

const ScheduleRow{T} = NamedTuple{(:factor, :resolution_h, :nx_out), Tuple{Int, T, Int}}

function _validate_odd_unique_seeds(seeds::NTuple{N, Int}) where {N}
    all(isodd, seeds) || throw(ArgumentError("All seeds must be odd, got seeds=$(seeds)"))
    @inbounds for i in 1:N
        for j in (i + 1):N
            seeds[i] == seeds[j] && throw(ArgumentError("Seeds must be unique, got duplicates in seeds=$(seeds)"))
        end
    end
    return nothing
end

function build_schedule_from_seeds!(
    schedule_out::Vector{ScheduleRow{T}},
    factors_tmp::Vector{Int},
    nx::Int,
    dx::T,
    seeds::NTuple{N, Int},
    min_factor::Int,
    include_full_domain::Bool,
) where {T <: Real, N}
    n_factors = 0
    has_full_domain = false

    @inbounds for seed in seeds
        f = seed
        while f < min_factor
            f <<= 1
        end
        while f <= nx
            n_factors += 1
            has_full_domain |= (f == nx)
            f <<= 1
        end
    end

    if include_full_domain && !has_full_domain
        n_factors += 1
    end

    resize!(factors_tmp, n_factors)
    idx = 1
    for seed in seeds
        f = seed
        while f < min_factor
            f <<= 1
        end
        while f <= nx
            factors_tmp[idx] = f
            idx += 1
            f <<= 1
        end
    end

    if include_full_domain && !has_full_domain
        factors_tmp[idx] = nx
    end

    sort!(factors_tmp)

    resize!(schedule_out, length(factors_tmp))
    @inbounds for i in eachindex(factors_tmp)
        f = factors_tmp[i]
        schedule_out[i] = (
            factor=f,
            resolution_h=T(f) * dx,
            nx_out=div(nx, f),
        )
    end

    return schedule_out
end

"""
    seed_factor_ladder(n::Int, seed::Int; min_factor::Int=1)

Return factors generated by `seed * 2^k <= n` as a tuple.
No allocations in hot path. Caller handles full domain separately.
"""
function seed_factor_ladder(n::Int, seed::Int; min_factor::Int=1)
    n >= 1 || throw(ArgumentError("n must be >= 1"))
    seed >= 1 || throw(ArgumentError("seed must be >= 1"))
    min_factor >= 1 || throw(ArgumentError("min_factor must be >= 1"))

    seed > n && return ()

    max_k = floor(Int, log2(div(n, seed)))
    factors = ntuple(k -> seed * (1 << (k - 1)), max_k + 1)
    
    return filter(f -> f >= min_factor, factors)
end

"""
    build_schedule_from_seeds!(schedule_out, factors_tmp, nx, dx; seeds, min_h=0, include_full_domain=true)

In-place schedule builder for hot-loop usage.

This method avoids per-call allocations by reusing caller-provided scratch buffers.

Assumptions (matching the original `array_utils.jl` intent):
- `seeds` are odd and unique (validated each call).
- Under odd+unique seeds, ladders are deterministic and do not overlap.

Scratch buffers:
- `schedule_out::Vector{ScheduleRow{T}}`: reusable output vector. Resized and overwritten each call.
- `factors_tmp::Vector{Int}`: temporary list of coarsening factors `f` from seed ladders.

Typical usage pattern:
1. Allocate `schedule_out` and `factors_tmp` once.
2. Call `build_schedule_from_seeds!` repeatedly inside your loop.
3. Read rows from returned `schedule_out`.

Example:
```julia
schedule_out = ScheduleRow{Float32}[]
factors_tmp = Int[]

for chunk in chunks
    build_schedule_from_seeds!(
        schedule_out,
        factors_tmp,
        nx,
        dx;
        seeds=(1, 31),
        min_h=Float32(1000),
        include_full_domain=true,
    )
    # use schedule_out...
end
```
"""
function build_schedule_from_seeds!(
    schedule_out::Vector{ScheduleRow{T}},
    factors_tmp::Vector{Int},
    nx::Int,
    dx::T;
    seeds::NTuple{N, Int},
    min_h::T=zero(T),
    include_full_domain::Bool=true,
) where {T <: Real, N}
    nx >= 1 || throw(ArgumentError("nx must be >= 1"))
    dx > zero(T) || throw(ArgumentError("dx must be > 0"))
    min_h >= zero(T) || throw(ArgumentError("min_h must be >= 0"))
    _validate_odd_unique_seeds(seeds)

    min_factor = max(1, ceil(Int, min_h / dx))
    return build_schedule_from_seeds!(
        schedule_out,
        factors_tmp,
        nx,
        dx,
        seeds,
        min_factor,
        include_full_domain,
    )
end

"""
    build_schedule_from_seeds(nx::Int, dx::T; seeds::NTuple{N,Int}, min_h::T=zero(T), include_full_domain::Bool=true) where {T,N}

Build a horizontal resolution schedule from a set of arbitrary odd seeds.
Each seed generates a ladder of factors `seed * 2^k <= nx`.
Returns a sorted vector of (factor, resolution_h, nx_out) tuples.
"""
function build_schedule_from_seeds(
    nx::Int,
    dx::T;
    seeds::NTuple{N, Int},
    min_h::T=zero(T),
    include_full_domain::Bool=true,
) where {T <: Real, N}
    schedule_out = ScheduleRow{T}[]
    factors_tmp = Int[]
    return build_schedule_from_seeds!(
        schedule_out,
        factors_tmp,
        nx,
        dx;
        seeds=seeds,
        min_h=min_h,
        include_full_domain=include_full_domain,
    )
end

"""
    coarsen2d_mean!(out, data, fx, fy)

Average `data` over non-overlapping `fx x fy` blocks and write into `out`.
`size(out)` must equal `(div(size(data,1), fx), div(size(data,2), fy))`.

Current edge policy is crop-by-division (consistent with existing package behavior).
"""
function coarsen2d_mean!(out::AbstractMatrix{T}, data::AbstractMatrix{T}, fx::Int, fy::Int) where {T <: Real}
    fx >= 1 || throw(ArgumentError("fx must be >= 1"))
    fy >= 1 || throw(ArgumentError("fy must be >= 1"))

    nx, ny = size(data)
    nxo = div(nx, fx)
    nyo = div(ny, fy)
    size(out, 1) == nxo || throw(DimensionMismatch("out size mismatch in dim 1"))
    size(out, 2) == nyo || throw(DimensionMismatch("out size mismatch in dim 2"))

    inv_area = one(T) / T(fx * fy)

    @inbounds for j in 1:nyo
        base_j = (j - 1) * fy + 1
        for i in 1:nxo
            base_i = (i - 1) * fx + 1
            acc = zero(T)
            for jj in 0:(fy - 1)
                for ii in 0:(fx - 1)
                    acc += data[base_i + ii, base_j + jj]
                end
            end
            out[i, j] = acc * inv_area
        end
    end

    return out
end

function coarsen2d_mean(data::AbstractMatrix{T}, fx::Int, fy::Int) where {T <: Real}
    nx, ny = size(data)
    out = similar(data, div(nx, fx), div(ny, fy))
    return coarsen2d_mean!(out, data, fx, fy)
end

"""
    coarsen3d_horizontal_mean!(out, data, fx, fy)

Apply 2D block means independently at each vertical index `k` of `(x,y,z)` data.
"""
function coarsen3d_horizontal_mean!(out::AbstractArray{T, 3}, data::AbstractArray{T, 3}, fx::Int, fy::Int) where {T <: Real}
    fx >= 1 || throw(ArgumentError("fx must be >= 1"))
    fy >= 1 || throw(ArgumentError("fy must be >= 1"))

    nx, ny, nz = size(data)
    nxo = div(nx, fx)
    nyo = div(ny, fy)
    size(out) == (nxo, nyo, nz) || throw(DimensionMismatch("out size mismatch for 3D coarsening"))

    inv_area = one(T) / T(fx * fy)

    @inbounds for k in 1:nz
        for j in 1:nyo
            base_j = (j - 1) * fy + 1
            for i in 1:nxo
                base_i = (i - 1) * fx + 1
                acc = zero(T)
                for jj in 0:(fy - 1)
                    for ii in 0:(fx - 1)
                        acc += data[base_i + ii, base_j + jj, k]
                    end
                end
                out[i, j, k] = acc * inv_area
            end
        end
    end

    return out
end

function coarsen3d_horizontal_mean(data::AbstractArray{T, 3}, fx::Int, fy::Int) where {T <: Real}
    nx, ny, nz = size(data)
    out = similar(data, div(nx, fx), div(ny, fy), nz)
    return coarsen3d_horizontal_mean!(out, data, fx, fy)
end

"""
    coarsen3d_vertical_mean!(out, data, fz)

Average `(x,y,z)` data in non-overlapping blocks of size `fz` along `z`.
Current edge policy is crop-by-division.
"""
function coarsen3d_vertical_mean!(out::AbstractArray{T, 3}, data::AbstractArray{T, 3}, fz::Int) where {T <: Real}
    fz >= 1 || throw(ArgumentError("fz must be >= 1"))

    nx, ny, nz = size(data)
    nzo = div(nz, fz)
    size(out) == (nx, ny, nzo) || throw(DimensionMismatch("out size mismatch for vertical 3D coarsening"))

    inv_fz = one(T) / T(fz)
    @inbounds for k in 1:nzo
        base_k = (k - 1) * fz + 1
        for j in 1:ny
            for i in 1:nx
                acc = zero(T)
                for kk in 0:(fz - 1)
                    acc += data[i, j, base_k + kk]
                end
                out[i, j, k] = acc * inv_fz
            end
        end
    end

    return out
end

function coarsen3d_vertical_mean(data::AbstractArray{T, 3}, fz::Int) where {T <: Real}
    nx, ny, nz = size(data)
    out = similar(data, nx, ny, div(nz, fz))
    return coarsen3d_vertical_mean!(out, data, fz)
end

"""
    conv3d_block_mean!(out, data, fx, fy, fz)
    conv3d_block_mean(data, fx, fy, fz)

Non-overlapping **3D** box average: each output voxel is the mean of one `fx×fy×fz` block.
Same numerics as mean pooling with kernel `(fx,fy,fz)` and stride `(fx,fy,fz)`, or a normalized
3D box convolution on valid positions.

For **means**, this matches applying `coarsen3d_horizontal_mean` then `coarsen3d_vertical_mean`
with the same factors (when `nx,ny,nz` divide evenly).

`data` is `(nx, ny, nz)`; `out` must be `(div(nx,fx), div(ny,fy), div(nz,fz))`. Partial blocks
at the end are dropped (crop-by-division), consistent with `coarsen2d_mean!`.
"""
function conv3d_block_mean!(
    out::AbstractArray{T, 3},
    data::AbstractArray{T, 3},
    fx::Int,
    fy::Int,
    fz::Int,
) where {T <: Real}
    fx >= 1 || throw(ArgumentError("fx must be >= 1"))
    fy >= 1 || throw(ArgumentError("fy must be >= 1"))
    fz >= 1 || throw(ArgumentError("fz must be >= 1"))

    nx, ny, nz = size(data)
    nxo = div(nx, fx)
    nyo = div(ny, fy)
    nzo = div(nz, fz)
    size(out) == (nxo, nyo, nzo) || throw(DimensionMismatch("out size mismatch for conv3d_block_mean"))

    inv_vol = one(T) / T(fx * fy * fz)
    @inbounds for k in 1:nzo
        base_k = (k - 1) * fz + 1
        for j in 1:nyo
            base_j = (j - 1) * fy + 1
            for i in 1:nxo
                base_i = (i - 1) * fx + 1
                acc = zero(T)
                for kk in 0:(fz - 1)
                    z = base_k + kk
                    for jj in 0:(fy - 1)
                        y = base_j + jj
                        for ii in 0:(fx - 1)
                            x = base_i + ii
                            acc += data[x, y, z]
                        end
                    end
                end
                out[i, j, k] = acc * inv_vol
            end
        end
    end
    return out
end

function conv3d_block_mean(data::AbstractArray{T, 3}, fx::Int, fy::Int, fz::Int) where {T <: Real}
    nx, ny, nz = size(data)
    out = similar(data, div(nx, fx), div(ny, fy), div(nz, fz))
    return conv3d_block_mean!(out, data, fx, fy, fz)
end

"""
    valid_box_output_extent(n, window, stride) -> Int

Number of valid starting positions along one axis (1-based origin), or `0` if `n < window`.
"""
function valid_box_output_extent(n::Int, window::Int, stride::Int)
    window >= 1 && stride >= 1 || throw(ArgumentError("window and stride must be >= 1"))
    n < window && return 0
    return div(n - window, stride) + 1
end

"""
    uniform_stride_for_valid_box(n, window, k_outputs) -> Int

**Uniform stride only** (used when `sliding_stride_*` is set in `spatial_info`, or for
experiments). Chooses one integer `stride` so `valid_box_output_extent(n, window, stride) ≤ k_outputs`,
maximizing the number of outputs under that cap and minimizing `|stride - ideal|` for
`ideal = (n-window)/(k_outputs-1)`.

This does **not** guarantee the last window is flush to the far edge when
`(n - window) % (k_outputs - 1) ≠ 0`. For **exactly** `k` placements with first start at
`1` and last start at `n - window + 1`, use [`valid_box_anchor_starts`](@ref) and the
`*_at_starts` convolutions (default sliding path when strides are not explicit).
"""
function uniform_stride_for_valid_box(n::Int, window::Int, k_outputs::Int)
    window >= 1 && k_outputs >= 1 || throw(ArgumentError("window and k_outputs must be >= 1"))
    n < window && return 1
    span = n - window
    if k_outputs == 1
        return max(1, span + 1)
    end
    ideal = span / (k_outputs - 1)
    best_s = 1
    best_out = -1
    best_dist = Inf
    for s in 1:max(1, span)
        out = div(span, s) + 1
        out > k_outputs && continue
        dist = abs(s - ideal)
        if out > best_out ||
            (out == best_out && dist < best_dist) ||
            (out == best_out && dist == best_dist && s < best_s)
            best_out = out
            best_dist = dist
            best_s = s
        end
    end
    best_out == -1 && return max(1, span)
    return best_s
end

"""
    valid_box_anchor_starts(n, window, k) -> Vector{Int}

`k` valid 1-based window **origin** indices along one axis, **including** `1` and
`n - window + 1`, with interior origins spaced by integer division. The returned length is
`min(k, L)` where `L = n - window + 1` is the count of distinct valid starts (so a single
full-domain window yields one anchor even if `k > 1`).

Example: `n=10`, `window=3` ⇒ last start `8`; `k=3` ⇒ `[1, 4, 8]` (not uniform stride).
"""
function valid_box_anchor_starts(n::Int, window::Int, k::Int)::Vector{Int}
    window >= 1 || throw(ArgumentError("window must be >= 1"))
    k >= 1 || throw(ArgumentError("k must be >= 1"))
    n < window && throw(DimensionMismatch("window exceeds n"))
    L = n - window + 1
    k_eff = min(k, L)
    k_eff == 1 && return Int[1]
    return Int[1 + div((i - 1) * (L - 1), k_eff - 1) for i in 1:k_eff]
end

function conv3d_valid_box_mean_at_starts!(
    out::AbstractArray{T, 3},
    data::AbstractArray{T, 3},
    wx::Int,
    wy::Int,
    wz::Int,
    ix::AbstractVector{Int},
    iy::AbstractVector{Int},
    iz::AbstractVector{Int},
) where {T <: Real}
    wx >= 1 && wy >= 1 && wz >= 1 || throw(ArgumentError("window sizes must be >= 1"))
    nx, ny, nz = size(data)
    nxo, nyo, nzo = length(ix), length(iy), length(iz)
    size(out) == (nxo, nyo, nzo) || throw(DimensionMismatch("out size mismatch for conv3d_valid_box_mean_at_starts"))
    inv_vol = one(T) / T(wx * wy * wz)
    @inbounds for koz in 1:nzo
        k0 = iz[koz]
        (k0 >= 1 && k0 + wz - 1 <= nz) || throw(DimensionMismatch("z anchor out of bounds"))
        for joz in 1:nyo
            j0 = iy[joz]
            (j0 >= 1 && j0 + wy - 1 <= ny) || throw(DimensionMismatch("y anchor out of bounds"))
            for ioz in 1:nxo
                i0 = ix[ioz]
                (i0 >= 1 && i0 + wx - 1 <= nx) || throw(DimensionMismatch("x anchor out of bounds"))
                acc = zero(T)
                for kk in 0:(wz - 1)
                    z = k0 + kk
                    for jj in 0:(wy - 1)
                        y = j0 + jj
                        for ii in 0:(wx - 1)
                            x = i0 + ii
                            acc += data[x, y, z]
                        end
                    end
                end
                out[ioz, joz, koz] = acc * inv_vol
            end
        end
    end
    return out
end

function conv3d_valid_box_mean_at_starts(
    data::AbstractArray{T, 3},
    wx::Int,
    wy::Int,
    wz::Int,
    ix::AbstractVector{Int},
    iy::AbstractVector{Int},
    iz::AbstractVector{Int},
) where {T <: Real}
    out = similar(data, length(ix), length(iy), length(iz))
    return conv3d_valid_box_mean_at_starts!(out, data, wx, wy, wz, ix, iy, iz)
end

function conv3d_valid_box_product_mean_at_starts!(
    out::AbstractArray{T, 3},
    x::AbstractArray{T, 3},
    y::AbstractArray{T, 3},
    wx::Int,
    wy::Int,
    wz::Int,
    ix::AbstractVector{Int},
    iy::AbstractVector{Int},
    iz::AbstractVector{Int},
) where {T <: Real}
    size(x) == size(y) || throw(DimensionMismatch("x and y must match shape"))
    wx >= 1 && wy >= 1 && wz >= 1 || throw(ArgumentError("window sizes must be >= 1"))
    nx, ny, nz = size(x)
    nxo, nyo, nzo = length(ix), length(iy), length(iz)
    size(out) == (nxo, nyo, nzo) || throw(DimensionMismatch("out size mismatch"))
    inv_vol = one(T) / T(wx * wy * wz)
    @inbounds for koz in 1:nzo
        k0 = iz[koz]
        (k0 >= 1 && k0 + wz - 1 <= nz) || throw(DimensionMismatch("z anchor out of bounds"))
        for joz in 1:nyo
            j0 = iy[joz]
            (j0 >= 1 && j0 + wy - 1 <= ny) || throw(DimensionMismatch("y anchor out of bounds"))
            for ioz in 1:nxo
                i0 = ix[ioz]
                (i0 >= 1 && i0 + wx - 1 <= nx) || throw(DimensionMismatch("x anchor out of bounds"))
                acc = zero(T)
                for kk in 0:(wz - 1)
                    z = k0 + kk
                    for jj in 0:(wy - 1)
                        yy = j0 + jj
                        for ii in 0:(wx - 1)
                            xi = i0 + ii
                            acc += x[xi, yy, z] * y[xi, yy, z]
                        end
                    end
                end
                out[ioz, joz, koz] = acc * inv_vol
            end
        end
    end
    return out
end

function conv3d_valid_box_product_mean_at_starts(
    x::AbstractArray{T, 3},
    y::AbstractArray{T, 3},
    wx::Int,
    wy::Int,
    wz::Int,
    ix::AbstractVector{Int},
    iy::AbstractVector{Int},
    iz::AbstractVector{Int},
) where {T <: Real}
    out = similar(x, length(ix), length(iy), length(iz))
    return conv3d_valid_box_product_mean_at_starts!(out, x, y, wx, wy, wz, ix, iy, iz)
end

"""
    conv3d_valid_box_mean!(out, data, wx, wy, wz; stride_h=1, stride_v=1, stride_z=1)

Valid (non-padded) 3D box average: each output cell `(io,jo,ko)` averages
`data[i0:(i0+wx-1), j0:(j0+wy-1), k0:(k0+wz-1)]` with
`i0 = 1 + (io-1)*stride_h`, etc.
"""
function conv3d_valid_box_mean!(
    out::AbstractArray{T, 3},
    data::AbstractArray{T, 3},
    wx::Int,
    wy::Int,
    wz::Int;
    stride_h::Int = 1,
    stride_v::Int = 1,
    stride_z::Int = 1,
) where {T <: Real}
    wx >= 1 && wy >= 1 && wz >= 1 || throw(ArgumentError("window sizes must be >= 1"))
    stride_h >= 1 && stride_v >= 1 && stride_z >= 1 || throw(ArgumentError("strides must be >= 1"))
    nx, ny, nz = size(data)
    nxo = valid_box_output_extent(nx, wx, stride_h)
    nyo = valid_box_output_extent(ny, wy, stride_v)
    nzo = valid_box_output_extent(nz, wz, stride_z)
    (nxo == 0 || nyo == 0 || nzo == 0) && throw(DimensionMismatch("window too large for data"))
    size(out) == (nxo, nyo, nzo) || throw(DimensionMismatch("out size mismatch for conv3d_valid_box_mean"))
    inv_vol = one(T) / T(wx * wy * wz)
    if nthreads() > 1 && nxo * nyo * nzo >= 2048
        @threads for io in 1:nxo
            i0 = 1 + (io - 1) * stride_h
            @inbounds for ko in 1:nzo
                k0 = 1 + (ko - 1) * stride_z
                for jo in 1:nyo
                    j0 = 1 + (jo - 1) * stride_v
                    acc = zero(T)
                    for kk in 0:(wz - 1)
                        z = k0 + kk
                        for jj in 0:(wy - 1)
                            y = j0 + jj
                            for ii in 0:(wx - 1)
                                x = i0 + ii
                                acc += data[x, y, z]
                            end
                        end
                    end
                    out[io, jo, ko] = acc * inv_vol
                end
            end
        end
    else
        @inbounds for ko in 1:nzo
            k0 = 1 + (ko - 1) * stride_z
            for jo in 1:nyo
                j0 = 1 + (jo - 1) * stride_v
                for io in 1:nxo
                    i0 = 1 + (io - 1) * stride_h
                    acc = zero(T)
                    for kk in 0:(wz - 1)
                        z = k0 + kk
                        for jj in 0:(wy - 1)
                            y = j0 + jj
                            for ii in 0:(wx - 1)
                                x = i0 + ii
                                acc += data[x, y, z]
                            end
                        end
                    end
                    out[io, jo, ko] = acc * inv_vol
                end
            end
        end
    end
    return out
end

function conv3d_valid_box_mean(
    data::AbstractArray{T, 3},
    wx::Int,
    wy::Int,
    wz::Int;
    stride_h::Int = 1,
    stride_v::Int = 1,
    stride_z::Int = 1,
) where {T <: Real}
    nx, ny, nz = size(data)
    nxo = valid_box_output_extent(nx, wx, stride_h)
    nyo = valid_box_output_extent(ny, wy, stride_v)
    nzo = valid_box_output_extent(nz, wz, stride_z)
    (nxo == 0 || nyo == 0 || nzo == 0) && throw(DimensionMismatch("window too large for data"))
    out = similar(data, nxo, nyo, nzo)
    return conv3d_valid_box_mean!(out, data, wx, wy, wz; stride_h, stride_v, stride_z)
end

function conv3d_valid_box_product_mean!(
    out::AbstractArray{T, 3},
    x::AbstractArray{T, 3},
    y::AbstractArray{T, 3},
    wx::Int,
    wy::Int,
    wz::Int;
    stride_h::Int = 1,
    stride_v::Int = 1,
    stride_z::Int = 1,
) where {T <: Real}
    size(x) == size(y) || throw(DimensionMismatch("x and y must match shape"))
    wx >= 1 && wy >= 1 && wz >= 1 || throw(ArgumentError("window sizes must be >= 1"))
    stride_h >= 1 && stride_v >= 1 && stride_z >= 1 || throw(ArgumentError("strides must be >= 1"))
    nx, ny, nz = size(x)
    nxo = valid_box_output_extent(nx, wx, stride_h)
    nyo = valid_box_output_extent(ny, wy, stride_v)
    nzo = valid_box_output_extent(nz, wz, stride_z)
    (nxo == 0 || nyo == 0 || nzo == 0) && throw(DimensionMismatch("window too large for data"))
    size(out) == (nxo, nyo, nzo) || throw(DimensionMismatch("out size mismatch"))
    inv_vol = one(T) / T(wx * wy * wz)
    if nthreads() > 1 && nxo * nyo * nzo >= 2048
        @threads for io in 1:nxo
            i0 = 1 + (io - 1) * stride_h
            @inbounds for ko in 1:nzo
                k0 = 1 + (ko - 1) * stride_z
                for jo in 1:nyo
                    j0 = 1 + (jo - 1) * stride_v
                    acc = zero(T)
                    for kk in 0:(wz - 1)
                        z = k0 + kk
                        for jj in 0:(wy - 1)
                            yy = j0 + jj
                            for ii in 0:(wx - 1)
                                xi = i0 + ii
                                acc += x[xi, yy, z] * y[xi, yy, z]
                            end
                        end
                    end
                    out[io, jo, ko] = acc * inv_vol
                end
            end
        end
    else
        @inbounds for ko in 1:nzo
            k0 = 1 + (ko - 1) * stride_z
            for jo in 1:nyo
                j0 = 1 + (jo - 1) * stride_v
                for io in 1:nxo
                    i0 = 1 + (io - 1) * stride_h
                    acc = zero(T)
                    for kk in 0:(wz - 1)
                        z = k0 + kk
                        for jj in 0:(wy - 1)
                            yy = j0 + jj
                            for ii in 0:(wx - 1)
                                xi = i0 + ii
                                acc += x[xi, yy, z] * y[xi, yy, z]
                            end
                        end
                    end
                    out[io, jo, ko] = acc * inv_vol
                end
            end
        end
    end
    return out
end

function conv3d_valid_box_product_mean(
    x::AbstractArray{T, 3},
    y::AbstractArray{T, 3},
    wx::Int,
    wy::Int,
    wz::Int;
    stride_h::Int = 1,
    stride_v::Int = 1,
    stride_z::Int = 1,
) where {T <: Real}
    nx, ny, nz = size(x)
    nxo = valid_box_output_extent(nx, wx, stride_h)
    nyo = valid_box_output_extent(ny, wy, stride_v)
    nzo = valid_box_output_extent(nz, wz, stride_z)
    out = similar(x, nxo, nyo, nzo)
    return conv3d_valid_box_product_mean!(out, x, y, wx, wy, wz; stride_h, stride_v, stride_z)
end

"""
    coarsen_fields_horizontal(fields, fx, fy)

Coarsen all 3D fields in `fields` with a shared `(fx, fy)`.
All fields must share the same size.
"""
function coarsen_fields_horizontal(fields::AbstractDict{K, A}, fx::Int, fy::Int) where {K, T <: Real, A <: AbstractArray{T, 3}}
    isempty(fields) && return Dict{K, A}()

    first_key = first(keys(fields))
    base_size = size(fields[first_key])
    for (name, arr) in pairs(fields)
        size(arr) == base_size || throw(DimensionMismatch("Field $(name) has size $(size(arr)) but expected $(base_size)"))
    end

    out = Dict{K, Array{T, 3}}()
    for (name, arr) in pairs(fields)
        out[name] = Array(coarsen3d_horizontal_mean(arr, fx, fy))
    end
    return out
end

"""
    coarsen_fields_vertical(fields, fz)

Coarsen all 3D fields in `fields` along the vertical axis by factor `fz`.
All fields must share the same size.
"""
function coarsen_fields_vertical(fields::AbstractDict{K, A}, fz::Int) where {K, T <: Real, A <: AbstractArray{T, 3}}
    isempty(fields) && return Dict{K, A}()

    first_key = first(keys(fields))
    base_size = size(fields[first_key])
    for (name, arr) in pairs(fields)
        size(arr) == base_size || throw(DimensionMismatch("Field $(name) has size $(size(arr)) but expected $(base_size)"))
    end

    out = Dict{K, Array{T, 3}}()
    for (name, arr) in pairs(fields)
        out[name] = Array(coarsen3d_vertical_mean(arr, fz))
    end
    return out
end

"""
    coarsen_dz_profile_factor(dz_profile, fz)

Coarsen a per-level thickness profile by summing each contiguous group of `fz` native layers.
Output length is `length(dz_profile) ÷ fz`.
"""
function coarsen_dz_profile_factor(dz_profile::AbstractVector{<:Real}, fz::Int)
    fz >= 1 || throw(ArgumentError("fz must be >= 1"))
    nz = length(dz_profile)
    rem(nz, fz) != 0 && throw(DimensionMismatch("dz_profile length $nz must be divisible by fz=$fz"))
    nzo = div(nz, fz)
    out = Vector{Float32}(undef, nzo)
    @inbounds for k in 1:nzo
        base = (k - 1) * fz + 1
        acc = Float32(0)
        for kk in 0:(fz - 1)
            acc += Float32(dz_profile[base + kk])
        end
        out[k] = acc
    end
    return out
end

"""
    coarsen_dz_profile_2x(dz_profile)

Coarsen vertical cell thickness profile by summing adjacent pairs.
If `length(dz_profile)` is odd, the top (last) entry is dropped — matching the legacy
binary vertical ladder (same as pairing the first `2 * (length ÷ 2)` levels).
"""
function coarsen_dz_profile_2x(dz_profile::AbstractVector{<:Real})
    nz = length(dz_profile)
    nzc = div(nz, 2)
    out = Vector{Float32}(undef, nzc)
    @inbounds for k in 1:nzc
        fk = 2k - 1
        out[k] = Float32(dz_profile[fk] + dz_profile[fk + 1])
    end
    return out
end

"""
    full_domain_mean_3d(data)

Compute per-level `(z)` full horizontal domain means for `(x,y,z)` data.
Returns a vector of length `nz`.
"""
function full_domain_mean_3d(data::AbstractArray{T, 3}) where {T <: Real}
    return vec(dropdims(Statistics.mean(data; dims=(1, 2)); dims=(1, 2)))
end

end # module
