module ArrayUtils

using Statistics: Statistics

export seed_factor_ladder,
    build_schedule_from_seeds,
    build_schedule_from_seeds!,
    coarsen2d_mean,
    coarsen2d_mean!,
    coarsen3d_horizontal_mean,
    coarsen3d_horizontal_mean!,
    coarsen3d_vertical_mean,
    coarsen3d_vertical_mean!,
    coarsen_fields_horizontal,
    coarsen_fields_vertical,
    coarsen_dz_profile_2x,
    full_domain_mean_3d

const ScheduleRow{T} = NamedTuple{(:factor, :resolution_h, :nx_out), Tuple{Int, T, Int}}

function _validate_odd_unique_seeds(seeds::NTuple{N, Int}) where {N}
    all(isodd, seeds) || throw(ArgumentError("All seeds must be odd, got seeds=$(seeds)"))
    @inbounds for i in 1:N
        for j in (i + 1):N
            seeds[i] == seeds[j] && throw(ArgumentError("Seeds must be unique, got duplicates in seeds=$(seeds)"))
        end
    end
    return nothing
end

function build_schedule_from_seeds!(
    schedule_out::Vector{ScheduleRow{T}},
    factors_tmp::Vector{Int},
    nx::Int,
    dx::T,
    seeds::NTuple{N, Int},
    min_factor::Int,
    include_full_domain::Bool,
) where {T <: Real, N}
    n_factors = 0
    has_full_domain = false

    @inbounds for seed in seeds
        f = seed
        while f < min_factor
            f <<= 1
        end
        while f <= nx
            n_factors += 1
            has_full_domain |= (f == nx)
            f <<= 1
        end
    end

    if include_full_domain && !has_full_domain
        n_factors += 1
    end

    resize!(factors_tmp, n_factors)
    idx = 1
    for seed in seeds
        f = seed
        while f < min_factor
            f <<= 1
        end
        while f <= nx
            factors_tmp[idx] = f
            idx += 1
            f <<= 1
        end
    end

    if include_full_domain && !has_full_domain
        factors_tmp[idx] = nx
    end

    sort!(factors_tmp)

    resize!(schedule_out, length(factors_tmp))
    @inbounds for i in eachindex(factors_tmp)
        f = factors_tmp[i]
        schedule_out[i] = (
            factor=f,
            resolution_h=T(f) * dx,
            nx_out=div(nx, f),
        )
    end

    return schedule_out
end

"""
    seed_factor_ladder(n::Int, seed::Int; min_factor::Int=1)

Return factors generated by `seed * 2^k <= n` as a tuple.
No allocations in hot path. Caller handles full domain separately.
"""
function seed_factor_ladder(n::Int, seed::Int; min_factor::Int=1)
    n >= 1 || throw(ArgumentError("n must be >= 1"))
    seed >= 1 || throw(ArgumentError("seed must be >= 1"))
    min_factor >= 1 || throw(ArgumentError("min_factor must be >= 1"))

    seed > n && return ()

    max_k = floor(Int, log2(div(n, seed)))
    factors = ntuple(k -> seed * (1 << (k - 1)), max_k + 1)
    
    return filter(f -> f >= min_factor, factors)
end

"""
    build_schedule_from_seeds!(schedule_out, factors_tmp, nx, dx; seeds, min_h=0, include_full_domain=true)

In-place schedule builder for hot-loop usage.

This method avoids per-call allocations by reusing caller-provided scratch buffers.

Assumptions (matching the original `array_utils.jl` intent):
- `seeds` are odd and unique (validated each call).
- Under odd+unique seeds, ladders are deterministic and do not overlap.

Scratch buffers:
- `schedule_out::Vector{ScheduleRow{T}}`: reusable output vector. Resized and overwritten each call.
- `factors_tmp::Vector{Int}`: temporary list of coarsening factors `f` from seed ladders.

Typical usage pattern:
1. Allocate `schedule_out` and `factors_tmp` once.
2. Call `build_schedule_from_seeds!` repeatedly inside your loop.
3. Read rows from returned `schedule_out`.

Example:
```julia
schedule_out = ScheduleRow{Float32}[]
factors_tmp = Int[]

for chunk in chunks
    build_schedule_from_seeds!(
        schedule_out,
        factors_tmp,
        nx,
        dx;
        seeds=(1, 31),
        min_h=Float32(1000),
        include_full_domain=true,
    )
    # use schedule_out...
end
```
"""
function build_schedule_from_seeds!(
    schedule_out::Vector{ScheduleRow{T}},
    factors_tmp::Vector{Int},
    nx::Int,
    dx::T;
    seeds::NTuple{N, Int},
    min_h::T=zero(T),
    include_full_domain::Bool=true,
) where {T <: Real, N}
    nx >= 1 || throw(ArgumentError("nx must be >= 1"))
    dx > zero(T) || throw(ArgumentError("dx must be > 0"))
    min_h >= zero(T) || throw(ArgumentError("min_h must be >= 0"))
    _validate_odd_unique_seeds(seeds)

    min_factor = max(1, ceil(Int, min_h / dx))
    return build_schedule_from_seeds!(
        schedule_out,
        factors_tmp,
        nx,
        dx,
        seeds,
        min_factor,
        include_full_domain,
    )
end

"""
    build_schedule_from_seeds(nx::Int, dx::T; seeds::NTuple{N,Int}, min_h::T=zero(T), include_full_domain::Bool=true) where {T,N}

Build a horizontal resolution schedule from a set of arbitrary odd seeds.
Each seed generates a ladder of factors `seed * 2^k <= nx`.
Returns a sorted vector of (factor, resolution_h, nx_out) tuples.
"""
function build_schedule_from_seeds(
    nx::Int,
    dx::T;
    seeds::NTuple{N, Int},
    min_h::T=zero(T),
    include_full_domain::Bool=true,
) where {T <: Real, N}
    schedule_out = ScheduleRow{T}[]
    factors_tmp = Int[]
    return build_schedule_from_seeds!(
        schedule_out,
        factors_tmp,
        nx,
        dx;
        seeds=seeds,
        min_h=min_h,
        include_full_domain=include_full_domain,
    )
end

"""
    coarsen2d_mean!(out, data, fx, fy)

Average `data` over non-overlapping `fx x fy` blocks and write into `out`.
`size(out)` must equal `(div(size(data,1), fx), div(size(data,2), fy))`.

Current edge policy is crop-by-division (consistent with existing package behavior).
"""
function coarsen2d_mean!(out::AbstractMatrix{T}, data::AbstractMatrix{T}, fx::Int, fy::Int) where {T <: Real}
    fx >= 1 || throw(ArgumentError("fx must be >= 1"))
    fy >= 1 || throw(ArgumentError("fy must be >= 1"))

    nx, ny = size(data)
    nxo = div(nx, fx)
    nyo = div(ny, fy)
    size(out, 1) == nxo || throw(DimensionMismatch("out size mismatch in dim 1"))
    size(out, 2) == nyo || throw(DimensionMismatch("out size mismatch in dim 2"))

    inv_area = one(T) / T(fx * fy)

    @inbounds for j in 1:nyo
        base_j = (j - 1) * fy + 1
        for i in 1:nxo
            base_i = (i - 1) * fx + 1
            acc = zero(T)
            for jj in 0:(fy - 1)
                for ii in 0:(fx - 1)
                    acc += data[base_i + ii, base_j + jj]
                end
            end
            out[i, j] = acc * inv_area
        end
    end

    return out
end

function coarsen2d_mean(data::AbstractMatrix{T}, fx::Int, fy::Int) where {T <: Real}
    nx, ny = size(data)
    out = similar(data, div(nx, fx), div(ny, fy))
    return coarsen2d_mean!(out, data, fx, fy)
end

"""
    coarsen3d_horizontal_mean!(out, data, fx, fy)

Apply 2D block means independently at each vertical index `k` of `(x,y,z)` data.
"""
function coarsen3d_horizontal_mean!(out::AbstractArray{T, 3}, data::AbstractArray{T, 3}, fx::Int, fy::Int) where {T <: Real}
    fx >= 1 || throw(ArgumentError("fx must be >= 1"))
    fy >= 1 || throw(ArgumentError("fy must be >= 1"))

    nx, ny, nz = size(data)
    nxo = div(nx, fx)
    nyo = div(ny, fy)
    size(out) == (nxo, nyo, nz) || throw(DimensionMismatch("out size mismatch for 3D coarsening"))

    inv_area = one(T) / T(fx * fy)

    @inbounds for k in 1:nz
        for j in 1:nyo
            base_j = (j - 1) * fy + 1
            for i in 1:nxo
                base_i = (i - 1) * fx + 1
                acc = zero(T)
                for jj in 0:(fy - 1)
                    for ii in 0:(fx - 1)
                        acc += data[base_i + ii, base_j + jj, k]
                    end
                end
                out[i, j, k] = acc * inv_area
            end
        end
    end

    return out
end

function coarsen3d_horizontal_mean(data::AbstractArray{T, 3}, fx::Int, fy::Int) where {T <: Real}
    nx, ny, nz = size(data)
    out = similar(data, div(nx, fx), div(ny, fy), nz)
    return coarsen3d_horizontal_mean!(out, data, fx, fy)
end

"""
    coarsen3d_vertical_mean!(out, data, fz)

Average `(x,y,z)` data in non-overlapping blocks of size `fz` along `z`.
Current edge policy is crop-by-division.
"""
function coarsen3d_vertical_mean!(out::AbstractArray{T, 3}, data::AbstractArray{T, 3}, fz::Int) where {T <: Real}
    fz >= 1 || throw(ArgumentError("fz must be >= 1"))

    nx, ny, nz = size(data)
    nzo = div(nz, fz)
    size(out) == (nx, ny, nzo) || throw(DimensionMismatch("out size mismatch for vertical 3D coarsening"))

    inv_fz = one(T) / T(fz)
    @inbounds for k in 1:nzo
        base_k = (k - 1) * fz + 1
        for j in 1:ny
            for i in 1:nx
                acc = zero(T)
                for kk in 0:(fz - 1)
                    acc += data[i, j, base_k + kk]
                end
                out[i, j, k] = acc * inv_fz
            end
        end
    end

    return out
end

function coarsen3d_vertical_mean(data::AbstractArray{T, 3}, fz::Int) where {T <: Real}
    nx, ny, nz = size(data)
    out = similar(data, nx, ny, div(nz, fz))
    return coarsen3d_vertical_mean!(out, data, fz)
end

"""
    coarsen_fields_horizontal(fields, fx, fy)

Coarsen all 3D fields in `fields` with a shared `(fx, fy)`.
All fields must share the same size.
"""
function coarsen_fields_horizontal(fields::AbstractDict{K, A}, fx::Int, fy::Int) where {K, T <: Real, A <: AbstractArray{T, 3}}
    isempty(fields) && return Dict{K, A}()

    first_key = first(keys(fields))
    base_size = size(fields[first_key])
    for (name, arr) in pairs(fields)
        size(arr) == base_size || throw(DimensionMismatch("Field $(name) has size $(size(arr)) but expected $(base_size)"))
    end

    out = Dict{K, Array{T, 3}}()
    for (name, arr) in pairs(fields)
        out[name] = Array(coarsen3d_horizontal_mean(arr, fx, fy))
    end
    return out
end

"""
    coarsen_fields_vertical(fields, fz)

Coarsen all 3D fields in `fields` along the vertical axis by factor `fz`.
All fields must share the same size.
"""
function coarsen_fields_vertical(fields::AbstractDict{K, A}, fz::Int) where {K, T <: Real, A <: AbstractArray{T, 3}}
    isempty(fields) && return Dict{K, A}()

    first_key = first(keys(fields))
    base_size = size(fields[first_key])
    for (name, arr) in pairs(fields)
        size(arr) == base_size || throw(DimensionMismatch("Field $(name) has size $(size(arr)) but expected $(base_size)"))
    end

    out = Dict{K, Array{T, 3}}()
    for (name, arr) in pairs(fields)
        out[name] = Array(coarsen3d_vertical_mean(arr, fz))
    end
    return out
end

"""
    coarsen_dz_profile_2x(dz_profile)

Coarsen vertical cell thickness profile by summing adjacent pairs.
"""
function coarsen_dz_profile_2x(dz_profile::AbstractVector{<:Real})
    nz = length(dz_profile)
    nzc = div(nz, 2)
    out = Vector{Float32}(undef, nzc)
    @inbounds for k in 1:nzc
        fk = 2k - 1
        out[k] = Float32(dz_profile[fk] + dz_profile[fk + 1])
    end
    return out
end

"""
    full_domain_mean_3d(data)

Compute per-level `(z)` full horizontal domain means for `(x,y,z)` data.
Returns a vector of length `nz`.
"""
function full_domain_mean_3d(data::AbstractArray{T, 3}) where {T <: Real}
    return vec(dropdims(Statistics.mean(data; dims=(1, 2)); dims=(1, 2)))
end

end # module
